/**
 * File generated by Magnet rest2mobile 1.1 - Apr 30, 2015 12:51:10 AM
 * @see {@link http://developer.magnet.com}
 */

package com.recycleview.tests.models.magnet.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.recycleview.tests.models.magnet.beans.*;

public interface RedditApi {

  /**
   * Generated from URL GET http://www.reddit.com/r/{subreddit}/.json?limit=50&after=0
   * GET r/{subreddit}/.json
   * @param subreddit  style:TEMPLATE
   * @param limit  style:QUERY
   * @param after  style:QUERY
   * @param listener
   * @return SubRedditResult
   */
  Call<SubRedditResult> getSubReddit(
     String subreddit, String limit,
     String after,
     StateChangedListener listener
  );


}
