/**
 * File generated by Magnet rest2mobile 1.1 - Apr 30, 2015 12:51:10 AM
 * @see {@link http://developer.magnet.com}
 */

package com.recycleview.tests.models.magnet.beans;

import java.util.List;

/**
 * Generated from json example
{
  "modhash" : "",
  "children" : [ {
    "kind" : "t3",
    "data" : {
      "domain" : "self.EarthPorn",
      "media_embed" : {
      },
      "subreddit" : "EarthPorn",
      "selftext_html" : "&lt;!--SC_OFF--&gt;&lt;divclass=\"md\"&gt;&lt;p&gt;Thisthreadisintendedtohelpthesubredditcommunicateandgetsomediscussiongoingregardingthestateofthesubreddit,qualityofsubmissions,qualityofmoderation,effectivenessofrulesatachievingthedesiredeffect,andsoon.Feelfreetoaskquestionsaboutphotographyortechniquesusedtocreatetheamazingimagesyouseeinthissubreddit.Alsofeelfreetocommentyourfavouritephotographers,aswellassomeoftheirwork.Pleasenotethatthisthreadisintendedtobeconstructive,sowhenyoucommentpleasetrytooffersuggestionstobalanceyourcritique.&lt;/p&gt;\n\n&lt;p&gt;Pleasesortcommentsby&amp;#39;new&amp;#39;tofindcommentsthatwouldotherwisebeburied.&lt;/p&gt;\n&lt;/div&gt;&lt;!--SC_ON--&gt;",
      "selftext" : "Thisthreadisintendedtohelpthesubredditcommunicateandgetsomediscussiongoingregardingthestateofthesubreddit,qualityofsubmissions,qualityofmoderation,effectivenessofrulesatachievingthedesiredeffect,andsoon.Feelfreetoaskquestionsaboutphotographyortechniquesusedtocreatetheamazingimagesyouseeinthissubreddit.Alsofeelfreetocommentyourfavouritephotographers,aswellassomeoftheirwork.Pleasenotethatthisthreadisintendedtobeconstructive,sowhenyoucommentpleasetrytooffersuggestionstobalanceyourcritique.\n\nPleasesortcommentsby'new'tofindcommentsthatwouldotherwisebeburied.\n",
      "user_reports" : [ ],
      "id" : "3410gr",
      "gilded" : 0,
      "archived" : false,
      "clicked" : false,
      "author" : "AutoModerator",
      "score" : 5,
      "over_18" : false,
      "hidden" : false,
        ...

 */

public class SubRedditResultData {

  
  private String after;

  
  private List<Child> children;

  
  private String modhash;

  public String getAfter() {
    return after;
  }
  public List<Child> getChildren() {
    return children;
  }
  public String getModhash() {
    return modhash;
  }

  /**
  * Builder for SubRedditResultData
  **/
  public static class SubRedditResultDataBuilder {
    private SubRedditResultData toBuild = new SubRedditResultData();

    public SubRedditResultDataBuilder() {
    }

    public SubRedditResultData build() {
      return toBuild;
    }

    public SubRedditResultDataBuilder after(String value) {
      toBuild.after = value;
      return this;
    }
    public SubRedditResultDataBuilder children(List<Child> value) {
      toBuild.children = value;
      return this;
    }
    public SubRedditResultDataBuilder modhash(String value) {
      toBuild.modhash = value;
      return this;
    }
  }
}
