/**
 * File generated by Magnet rest2mobile 1.1 - Apr 30, 2015 12:51:10 AM
 * @see {@link http://developer.magnet.com}
 */

package com.recycleview.tests.models.magnet.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;

import com.recycleview.tests.models.magnet.beans.*;

public class RedditApiFactory extends ControllerFactory<RedditApi> {
  public RedditApiFactory(MagnetMobileClient magnetClient) {
    super(RedditApi.class, RedditApiSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller RedditApi
  public static class RedditApiSchemaFactory extends AbstractControllerSchemaFactory {
    private static RedditApiSchemaFactory __instance;

    public static synchronized RedditApiSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new RedditApiSchemaFactory();
      }

      return __instance;
    }

    private RedditApiSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getSubReddit
      JMethod method1 = addMethod("getSubReddit",
        "r/{subreddit}/.json",
        "GET",
        SubRedditResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://www.reddit.com");
      method1.addParam("subreddit",
        "TEMPLATE",
        String.class,
        null,
        "",
        false);
    }

  }

}
